spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    password: password
  application:
    name: employee-service
  jpa:
    spring:
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
  cloud:
    config:
      import-check : 
       enabled : false
      fail-fast: true
      retry:
        max-attempts: 20
        max-interval: 15000
        initial-interval: 10000
      discovery:
        enabled: true
        service-id: CONFIG-SERVER


server:
  port: '8081'
  
employee-service:
   value: 'Employee Service Local Environment'
